name: Ping Supabase

on:
  schedule:
    - cron: '0 0 */5 * *'  # every 5 days at midnight UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl SnapNote Backend
        run: |
          echo "Pinging backend to keep Supabase alive..."
          curl -s -w "%{http_code}\n" -o /dev/null https://snapnote-backend-8prh.onrender.com/api/notes/ping


